deploy/main.bicep

Addressing issue: https://github.com/microsoft/semantic-kernel/issues/1702
Instead of mapping / to /healthz, we decided to disable alwaysOn and enable App Service health check. This is because mapping / to /healthz creates a dependency on the deployment setup and makes the code harder to maintain, i.e when alwaysOn is disabled, there is really not point at mapping the route. Thus, disabling alwaysOn and enabling App service health check is a cleaner solution.

Disable alwaysOn and enable health check

---

webapi/CopilotChatWebApi.csproj
webapi/Options/AzureCognitiveSearchOptions.cs
webapi/README.md
webapi/SemanticKernelExtensions.cs
webapi/ServiceExtensions.cs
webapi/appsettings.json

We want to have support for Microsoft's vector solution.
Add support for Azure Cognitive Search's Vector Search

Add support for Azure Cognitive Search's Vector Search

---

.github/workflows/copilot-deploy-pipeline.yml

When something is pushed to main we trigger the deployment to our int environment. If a new push happens when the pipeline is already running, the current run should be canceled. 
Setting up CI/CD pipeline to cancel when a new push happens.

Setting up CI/CD pipeline to cancel when a new push happens.

---

webapp/src/components/chat/chat-history/ChatHistoryItem.tsx
webapp/src/components/chat/chat-history/UserFeedbackActions.tsx
webapp/src/components/shared/BundledIcons.tsx
webapp/src/libs/models/ChatMessage.ts
webapp/src/redux/features/app/appSlice.ts
webapp/src/redux/features/conversations/conversationsSlice.ts
webapp/src/styles.tsx

Added RLFH UI to demonstrate users can easily add this capability to their chatbot if they wanted.  
> This feature is for demonstration purposes only. We don't actually hook up to the server to store the human feedback or send it to the model. 
Details:
- RLFH actions will only show on the most recent chat message in which the author is `bot`.
- If user takes action, icon will be rendered to reflect action.
- Data is only stored in frontend state. If app refreshes, all RLFH across all chats will be reset.
Actions on chat message:
Once user takes actions:
Future work 
- Add ability to turn of RLHF in settings dialog + add help link to docs there
~~- [ ] All unit tests pass, and I have added new tests where possible~~

📝 RLFH UX Skeleton

---

webapp/src/components/chat/persona/PromptEditor.tsx
webapp/src/components/chat/tabs/PersonaTab.tsx

When users are switching between conversations, the prompt editor may not update its contents if the prompt has been edited but not saved. This is because the value state is not updated when the original prompts of two chats are the same, the useEffect hook will not get triggered.
1. Make an extra dependency on the chatId to make the value state is updated each time users switch conversations.
2. Increase the height of the text area in the prompt editor.

Fix Persona tab state not updated bug

---

webapi/CopilotChat/Skills/ChatSkills/ExternalInformationSkill.cs
webapp/src/components/chat/plan-viewer/PlanJsonViewer.tsx
webapp/src/components/chat/plan-viewer/PlanViewer.tsx
webapp/src/components/chat/tabs/PlansTab.tsx

Add a plans tab to show created plans..
1. Add a plans tab.
2. Add a plan json viewer to allow users to see the plan written in Json.

Add plans tab

---

.github/labeler.yml
.github/workflows/label-pr.yml

adds the label to PRs that are newly created so that we don't have to.
also adds the 'dependencies' label to any change of the `yarn.lock` file

Add "PR: ready for review" to all PRs when they are first created

---

webapi/CopilotChat/Controllers/ChatMemoryController.cs

logging fields that can be passed by the user (e.g. route params) is flagged as a High sev issue by CodeQL:
https://github.com/microsoft/chat-copilot/security/code-scanning/1
suggested fix is to remove new line characters from the input.

Resolve CodeQL alerts by sanitizing route input

---

README.md
webapi/appsettings.json
webapp/.env.example
webapp/src/Constants.ts

I want to authorize the calls from web app to web api via Azure AD (Entra ID). The application is prepared to use this feature but it's not fully implemented.  
This PR adds the required changes in the web app and the web api projects. It also contains configuration instructions.  
It resolves the issue #38 .
- adds `REACT_APP_AAD_API_SCOPE` to `Constants.ts` to request `access_as_user` scope via MSAL
- extends .env.example with the new introduced `REACT_APP_AAD_API_SCOPE` variable
- adds `Authorization:AzureAd:Audience` key to web api for request authorization checks
- adds a configuration instruction to `README.md`

Add configuration for web api auth via Azure AD, and extend readme

---

webapi/CopilotChat/Models/CreateChatResponse.cs
webapp/src/components/chat/persona/PromptEditor.tsx
webapp/src/components/chat/tabs/PersonaTab.tsx
webapp/src/libs/hooks/useChat.ts
webapp/src/libs/models/ChatSession.ts
webapp/src/libs/services/ChatService.ts

The API chatSession/create was not returning the full chatSession object, which caused issues where the webapp was not able to get some properties from the new chat session.
Return the full chatSession object along with the initial chat message.

Let chatSession/create return the full chatSession object

---

deploy/deploy-azure.ps1
deploy/deploy-azure.sh

Add ability to set Web App region in deployment - Fixes #17
 
This PR adds support to the `deploy-azure.ps1` and `deploy-azure.sh` files to pass through the region to deploy the Static Web App to. This will default to `westus2 and is set in the .PS1/SH files.
This enables deploying all the resources to the same region, even though Static Web Apps is supported in only a few regions. The one region that all resource types are supported in is WestEurope.
Tests:
`azure-deploy.ps1`
`azure-deploy.sh`

Added support for setting Web App region in deployment - Fixes #17

---

deploy/README.md

- Fixing broken deploy to azure button in deployment README.
- Additional formatting

Fixing broken deploy to azure button in deployment README.

---

.gitignore
webapi/Controllers/ChatController.cs

Updated OpenApiPlugin paths from `CopilotChat/Skills` to `Skills` in ChatController.cs.
Also added autogenerated sln file to .gitignore
~~- [ ] All unit tests pass, and I have added new tests where possible~~

🔧 Update OpenApiPlugin paths

---

.github/workflows/memorypipeline-build.yml
.vscode/settings.json
CopilotChat.sln
memorypipeline/Builder.cs
memorypipeline/Program.cs
memorypipeline/SemanticMemoryPipelineService.csproj
memorypipeline/appsettings.json
memorypipeline/nuget.config

Semantic memory pipeline service

---

.gitignore
webapp/src/App.tsx
webapp/src/components/views/BackendProbe.tsx
webapp/src/components/views/Error.tsx
webapp/src/components/views/Loading.tsx
webapp/src/components/views/index.ts
webapp/src/styles.tsx

Added new app state for setting user info, refactored app views, and added shared styles for informative views.
This is a fix for a bug where the webapp would get stuck on the Loading Chats page. Something with SSO caused this.
- The App component now transitions to a SettingUserInfo state after successfully discovering the backend, and then to the LoadingChats state after successfully setting the active user info.
- The user info status text in the App component has been updated to display a default message while fetching user information, and an error component has been added to display an error message at view level. 
- A new useSharedClasses hook has been added to provide a set of shared styles for informative views. 
-  The BackendProbe component has also been updated to use the …

🚀 Adding new app state to handle user info

---

.github/workflows/copilot-deploy-pipeline.yml

Problem: when using the reusable workflow "copilot-build-backend.yml" from "copilot-deploy-pipeline.yml", the environment secrets do not propagate. 
Hack: copied the build workflow directly to the deploy workflow. This will create code duplication but will allow the deployment workflow to pass. This will get remove once we have the public Semantic Memory packages.

Hack Github action: no reusable workflow

---

README.md

A user has been unable to run the primary Readme ps scripts (e.g., scripts\Install.ps1) due to the error:
"File <ps script> cannot be loaded. The file <ps script> is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170."
Adds note directing user to official documentation pages on changing execution policy or unblocking the script.

Update Readme with note on execution policy.

---

webapi/Controllers/DocumentImportController.cs
webapi/Options/DocumentMemoryOptions.cs
webapi/Program.cs
webapi/appsettings.json

Responding to customer feedback on:
1. Document memory UX
1. Debug output
- When debugger is attached locally, appliication insight tracing is not written to the debug output.
- Larger document chunks with overlap provide a more coherent view of memories.  1000 tokens just isn't that much.
**Current:**
**Azure AI Playground:**
**Tuned:**

Tuned: Document chunking parameters and debug output (customer input)

---

scripts/deploy/deploy-azure.ps1
scripts/deploy/deploy-azure.sh
scripts/deploy/main.bicep
scripts/deploy/main.json
webapi/CopilotChatWebApi.csproj
webapi/Extensions/SemanticKernelExtensions.cs
webapi/Options/MemoryStoreOptions.cs
webapi/Options/PostgresOptions.cs
webapi/appsettings.json

I would like to provide a production-grade PaaS solution to store the vector database.
It provides PostgreSQL database support for memory. We can now use Azure Database for PostgreSQL or CosmosDB for PostgreSQL.
Fixes #166 
I added configuration support for PostgreSQL. in the kernel initialization. 
Furthermore I updated the deployment script to support this configuration.
> Note: In the deployment scripts, I've added the SqlAdminPassword parameter, which must be supplied during provisioning. I intentionally named it without the PostgreSQL name, as I also worked on implementing SQL Server Memory store in the SK repository. This parameter could be used by both databases during deployment.
> Not found test project on the API part ;(

Add postgresql memory store

---

webapp/src/redux/app/store.ts
webapp/src/redux/features/message-relay/signalRHubConnection.ts
webapp/src/redux/features/message-relay/signalRMiddleware.ts

The app currently attempts to establish the Signal R connection before validating the environment file. If the .env file is missing, 
the app won't be able to establish the signal R connection since it needs the backend URL.
Delay the attempt to establish the signal R connection to only when the connection is needed. This allows the error of a missing/incorrect .env file to be shown.

Encapsulate signalR hub connection instance

---

webapi/Skills/ChatSkills/ChatSkill.cs

Customer reported stale plug-in results.  Re-ordering prompt to include plug-in results last may impact prioritizing this data for certain cases.  (Isolated testing indicates that the model can respond to priority hints via ordering, but other factors may influence model behavior as well...such as chat history or memory presenting stronger semantic context.)
Move planner results to after chat-history:
```
[SOURCE START]
This is the result of invoking the functions listed after "PLUGINS USED:" to retrieve additional information outside of the data you were trained on. You can use this data to help answer the user's query.
PLUGINS USED: ListPluginPlugin.GetList.
RESULT: {
"content": "eba26d18-b4bb-46d4-b6b6-cbf60d4312e8\n12ed4781-5b22-48a0-b4e9-a351e546e7ff\n90605eb2-51ce-4058-8ae0-dfbe5ed45 …
```

Re-ordered plug-in result to be included _after_ chat-history

---

scripts/deploy/deploy-azure.ps1

deploy-azure.ps1 gave the following error when no sqlAdminPassword value was provided:
Cannot process argument transformation on parameter 'SqlAdminPassword'. Cannot convert the "" value of type "System.String" to type "System.Security.SecureString".
Use  null value instead of an empty string

Fix problem when sqlAdminPassword is not provided

---

webapi/Controllers/DocumentImportController.cs

Reported by customer in https://github.com/microsoft/chat-copilot/issues/218
Use null-coalesce operator to return false when service null

Fix Null Reference on Content-Saftey service

---

webapi/Extensions/ServiceExtensions.cs
webapi/Options/ContentSafetyOptions.cs

```
Unhandled exception. Microsoft.Extensions.Options.OptionsValidationException: DataAnnotation validation failed for 'ContentSafetyOptions' members: '' with the error: ''Enabled' must be a string.'.
at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
at System.Lazy`1.CreateValue()
at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
at Microsoft.Extensions.DependencyInjection.OptionsBuilderExtensions.<>c__DisplayClass0_1`1.<ValidateOnStart>b__1()
at …
```

Tweak ContentSafetyOptions.Enabled attribution and stream-line ServiceExtensiosn

---

.github/workflows/copilot-build-backend.yml
.github/workflows/dotnet-format.yml

There is currently no C# format check workflow for PRs. There is a workflow step in copilot-build-backend.yml that checks the format for the webapi, but that happens after the build step.
There are two .Net projects in the repo (soon to be three). It's better to have a workflow that checks the format for the entire repo, instead of having multiple steps scattered around different workflows.

Add a dotnet format check workflow

---

README.md
scripts/deploy/README.md

When setting up AAD Auth, an additional step is needed to provide consent for the frontend to access the backend for some tenants. Update the READMEs to include this step.
This is solely a documentation update.

Add missing step to README instructions for enabling auth

---

README.md

This fixes incorrect documentation when trying to setup the azure application permissions for the frontend.
When adding the api permissions for the first time to the frontend, the "My APIs" will actually be empty:
(you can ignore the "hidden" - thats another app we have developed)
Instead the previously created exposure of the backend can only be found in the "APIs my organization uses" tab:

Fix incorrect tab mentioned for frontend app registration

---

scripts/deploy/main.json

Building `main.json` from `main.bicep` to get latest changes.

Building main.json from main.bicep to get latest changes.

---

.github/workflows/copilot-test-e2e.yml
webapp/src/App.tsx
webapp/src/components/chat/chat-list/ListItemActions.tsx
webapp/src/components/chat/invitation-dialog/InvitationCreateDialog.tsx
webapp/src/components/header/UserSettingsMenu.tsx
webapp/src/components/header/settings-dialog/SettingSection.tsx
webapp/src/components/header/settings-dialog/SettingsDialog.tsx
webapp/src/components/views/Login.tsx
webapp/tests/chat.test.ts
webapp/tests/testsBasic.ts
webapp/tests/testsMultiuser.ts
webapp/tests/utils.ts

The scenario tests have been failing for a long time, due to rapid changes coming into the repo. It's time to fix them. 
1. Skip Jira plugin test since we don't have a managed account.
2. Fix all other tests.
Will create an item to track the GitHub and Jira plugin tests.

Fix scenario tests

---

CopilotChat.sln
integration-tests/ChatCopilotIntegrationTest.cs
integration-tests/ChatCopilotIntegrationTests.csproj
integration-tests/HealthzTests.cs
integration-tests/README.md
integration-tests/testsettings.json

We want to make our CI/CD pipeline more robust
Added an integration test project.

Add integration test project

---

webapp/package.json
webapp/src/components/chat/chat-history/ChatHistoryTextContent.tsx
webapp/src/components/utils/TextUtils.tsx
webapp/yarn.lock

When requesting `generate a table of fruits` or `generate some code to count from 1 to 200` the response will contain markdown: 
However Markdown can not be rendered in the frontend. This PR fixes it by adding a markdown rendering library and making use of it:
This also avoids using `dangerouslySetInnerHTML` attribute. The library `remark-gfm` is used because `react-markdown` does not support tables out of the box. 
This is how urls or links would be rendered:

render chat messages as markdown

---

webapp/tests/chat.test.ts
webapp/tests/testsBasic.ts
webapp/tests/testsMultiuser.ts
webapp/tests/testsPlanner.ts
webapp/tests/utils.ts

We have to security warning from Code scanning:
https://github.com/microsoft/chat-copilot/security/code-scanning/14
https://github.com/microsoft/chat-copilot/security/code-scanning/15
Replace regex with startsWith.

Mitigate security warning from regex with env var

---

.github/workflows/copilot-build-backend.yml
.github/workflows/copilot-deploy-backend.yml
.github/workflows/copilot-deploy-environment.yml
.github/workflows/copilot-deploy-pipeline.yml
.github/workflows/copilot-run-integration-tests.yml
integration-tests/ChatCopilotIntegrationTest.cs
integration-tests/README.md
integration-tests/testsettings.json

We want to run integration tests as part of our CI/CD pipeline
Run integration tests upon check-ins to merge

Integration tests workflow

---

webapi/Controllers/ChatHistoryController.cs

Add `$"chat-documents-{chatId}"` to filter for `memoryCollections`. Delete chat currently only removing two indexes and leaving one orphaned.
Noticed this using our INT/proud-river deployment.
Here is the index naming currently used:

Delete-chat fix to also remove document index

---

README.md

Adding text to clarify that the requirements still need to be met before deploying to Azure.

Clarify requirements before deploying to Azure

---

webapi/Controllers/ChatController.cs
webapi/Options/ServiceOptions.cs
webapi/Skills/ChatSkills/ChatSkill.cs
webapi/Skills/ChatSkills/CopilotChatPlanner.cs
webapi/Skills/ChatSkills/DocumentMemorySkill.cs
webapi/Skills/ChatSkills/ExternalInformationSkill.cs
webapi/Skills/ChatSkills/SemanticChatMemorySkill.cs
webapi/appsettings.json
webapp/src/libs/services/BaseService.ts

This PR adds a TimeoutLimitInS option in appsettings, which is used as the CancellationToken timeout if specified. The CancellationToken is used to monitor for cancellation requests.
This PR fixes a bug by passing the cancellation token to all async methods of ChatSkill. If a timeout limit is not specified in appsettings, a cancellation token source without a timeout is created and passed.

Adding Timeout Limit option for /chat requests

---

webapi/Controllers/ChatController.cs
webapi/CopilotChatWebApi.csproj
webapi/Extensions/SemanticKernelExtensions.cs
webapi/Options/PlannerOptions.cs
webapi/Skills/ChatSkills/ChatSkill.cs
webapi/Skills/ChatSkills/CopilotChatPlanner.cs
webapi/Skills/ChatSkills/DocumentMemorySkill.cs
webapi/Skills/ChatSkills/ExternalInformationSkill.cs
webapi/Skills/ChatSkills/SemanticChatMemoryExtractor.cs
webapi/Skills/TokenUtilities.cs
webapi/appsettings.json

Update SK from 0.19.230804.2-preview to 0.21.230828.2-preview
The following changes have been made because of this update:
1. Move away from using the logger (deprecated/removed) in SKcontext. Instead, it's going to use the logger that's passed in to the ChatSkill.
2. Planner will always retry regardless of the error type (when is configured) as a result of the removal of PlanningException and KernelException along with the error codes.

Update SK from 0.19.230804.2-preview to 0.21.230828.2-preview

---

webapi/Controllers/ChatController.cs
webapi/Options/PlannerOptions.cs
webapi/appsettings.json
webapp/src/App.tsx

Two small changes in this PR:
1. Using `${account.localAccountId}.${account.tenantId}` over account.homeAccountId to match how UserId is constructed for chat messages in webapi. 
2. Adds another option in appsettings to allow users to set a timeout limit for plugin calls. 
1. How userId is constructed in webapi:
-  `${account.localAccountId}.${account.tenantId}` is more accurate for guest accounts, and it is not equivalent to the homeAccountid (which = `{userIdInHomeTenant}.{HomeTenantId}` for guest accounts).
2. Default HttpClient.Timeout is 100 seconds; customer request to allow this to be configurable to accomodate plugins that take a long time.

Adding option for plugin timeout + using proper userId for guest accounts

---

webapi/Controllers/MaintenanceController.cs

Incorrect controller route/method signature causing build error
```
D:\a\chat-copilot\chat-copilot\webapi\Controllers\MaintenanceController.cs(50,55): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [D:\a\chat-copilot\chat-copilot\webapi\CopilotChatWebApi.csproj]
```

Fix async signature

---

webapi/Controllers/BotController.cs
webapi/Controllers/ChatMemoryController.cs
webapi/Skills/ChatSkills/DocumentMemorySkill.cs
webapi/Skills/ChatSkills/SemanticChatMemoryExtractor.cs
webapi/Skills/ChatSkills/SemanticChatMemorySkill.cs

Customer discovered this issue today and it will block anyone who tries to create a new chat.
SK used to throw SKException.  Now they are allowing an Azure specific excepetion type to bubble-up for ACS connector and could be anything for different connectors.
This is exacerbated by a second latent SK behavior that a vector-database container/index requires a write before allowing a successful (non-exceptional) read.  Previously chat-copilot was catching these exceptions as SKException.  Now they are uncaught.  This change fixes that.

Fix Exception catch block for vector-storage connector

---

README.md
webapi/README.md
webapp/README.md

1. Why is this change required? Confusion on getting-started abounds!
2. What problem does it solve? sub-readmes provided inconsistent basic getting-started info.
3. What scenario does it contribute to?  attempting to remove confusion around getting started
4. If it fixes an open issue, please link to the issue here. https://github.com/microsoft/chat-copilot/issues/344
This removes duplicate or incomplete information from the sub-readmes in webapp/ and webapi/ on basic getting started.  It redirects users to the main instruction readme, and also points to the learn docs getting started guide (which should be the ONLY duplicate of these instructions).
This change does NOT:
- attempt to update detailed development or debug information on the backend.  That falls under a separate task.
- …

Update sub-readmes for getting started

---

webapp/src/components/chat/ChatInput.tsx
webapp/src/components/chat/chat-list/ChatList.tsx
webapp/src/components/header/settings-dialog/SettingSection.tsx
webapp/src/libs/hooks/useChat.ts
webapp/src/redux/features/conversations/ChatState.ts
webapp/src/redux/features/conversations/conversationsSlice.ts

A couple of issues:
1. Multi-user chat sessions are filtered out in the loadChats method if the feature is disabled. When the feature is enabled, it doesn't call loadChats again, making it impossible to retrieve multi-user chat sessions. 
2. Supposed a user has only multi-user chat session, when the app first starts, all the multi-user chat sessions will be filtered out but the app doesn't call create chat, leaving the user with no chat to interact with.
3. the initial selectedId is the id of the first chat session returned by the service. If the first chat session is a multi-user chat session, the app will crash because the first chat session is filtered out and the selectedId becomes invalid.
Address all the above.

Fix multi-user chat feature toggle behavior

---

webapi/README.md
webapi/Skills/ChatSkills/ChatSkill.cs
webapi/Storage/CosmosDbContext.cs
webapi/Storage/IRepository.cs
webapi/Storage/IStorageEntity.cs
webapi/appsettings.json

Some changes to complement [partition key change](https://github.com/microsoft/chat-copilot/pull/240/files#diff-f9c37b8a51287ee8b7d42811b02d2ee33e4bcb565a155b358216519494eb38a9):
- Documentation updates to make partition key requirements more clear
- Using chatId as partition key when updating chat message state 
- Using partition key on upsert
~- [ ] All unit tests pass, and I have added new tests where possible~

Querying chat messages with partition key

---

webapi/CopilotChatWebApi.csproj

upon testing the update to `System.IdentityModel.Tokens.Jwt` in #355, I noticed that the package, as well as 2 others, are unused.
- removes  `System.IdentityModel.Tokens.Jwt`, `Microsoft.SemanticKernel.Skills.Web`, and `Microsoft.SemanticKernel.Planning.StepwisePlanner`.

Remove unused webapi packages

---

webapi/Program.cs

Customer had complained about error page when launching API for debugging.  They thought they had made a mistake and the API wasn't running correctly.
Redirect "/" to swagger UI for dev environmetn.

Dev UX - Redirect root path to swagger

---

integration-tests/ChatCopilotIntegrationTests.csproj
webapi/Controllers/ChatController.cs
webapi/CopilotChatWebApi.csproj
webapi/Extensions/SemanticKernelExtensions.cs
webapi/Models/Response/BotResponsePrompt.cs
webapi/Skills/ChatSkills/ChatSkill.cs
webapi/Skills/TokenUtilities.cs
webapp/src/libs/services/BaseService.ts

This pull request updates the SK package and includes several updates and improvements to the project:
- Tokenizer change
- Error handling updates
- Chat optimizations
- The `SharpToken` package has been added, and `SemanticKernel` packages have been updated to their latest preview versions [dotnet-0.24.230918.1-preview](https://github.com/microsoft/semantic-kernel/releases/tag/dotnet-0.24.230918.1-preview).
- The ChatSkill has been updated to improve performance and bypass audience extraction for the default user. 
- Update `TokenUtilities.TokenCount` to use custom SharpToken token counter implementation with cl100k_base encoding for calculating the number of tokens in a string, improving the accuracy and consistency of token counting in the project. Remove unused code for determining …

Updating SK to dotnet-0.24.230918.1-preview

---

.github/workflows/copilot-build-memorypipeline.yml

Sometimes, we just want the memory pipeline executable without running the whole deployment pipeline.
Add option to manually build memory pipeline executable in GitHub workflow

Add option to manually build memory pipeline executable

---

.github/labeler.yml

this label will also be removed, since all PRs not marked in Draft should be ready to review.

Stop adding "PR: ready for review" to all PRs

---

webapi/Controllers/ChatMemoryController.cs
webapi/Models/Request/SemanticMemoryType.cs
webapi/Options/PromptsOptions.cs
webapi/Skills/ChatSkills/SemanticChatMemoryExtractor.cs
webapi/appsettings.json

Currently the memory retrieval API requires the name of the memory as input, however, the memoryName is something that's configured in the backend and is not known by external clients. This PR refactors things to use a memoryType based on a stable enum as the public interface to the API which allows the memoryName to remain a configuration detail of the backend.   
-->
See issue #388

Using semantic memory type enum instead of string in API contract.

---

scripts/deploy/package-memorypipeline.sh
scripts/deploy/package-webapi.sh

Running the packaging bash scripts in the repo will result in the following error:
This is caused by un-escaped characters in the build options.
Fix the issue by escaping the characters in the build options.

Fix packaging bash scripts

---

webapi/Controllers/ChatMemoryController.cs

Address code scanning alert by sanitizing the `memoryType` parameter in `ChatMemoryController` before logging.

Sanitize log entry for memoryType

---

webapp/src/components/chat/plan-viewer/PlanViewer.tsx
webapp/src/components/chat/tabs/PlansTab.tsx
webapp/src/libs/models/Plan.ts

Fixes #438 
Old plans do not have the `userIntent` or `originalUserInput` fields, so use the plan description as a fallback to populate the goal.

Fix null dereference from empty intent/input

---

.github/workflows/copilot-deploy-plugins.yml

There is a copy & paste error in the deploy plugin workflow file.
Fix the error.

Update plugin deploy workflow name

---

webapi/Skills/ChatSkills/ChatSkill.cs
webapp/src/components/chat/plan-viewer/PlanDialogView.tsx
webapp/src/libs/hooks/useChat.ts
webapp/src/libs/models/Plan.ts

Returning all plan errors as embedded bot response message. Before, it would just be shown as a transient alert on the webapp. This allows us to maintain error context across chat sessions. 
On initial execution then re-run:
And added disclaimer to confirmation dialog
~- [ ] All unit tests pass, and I have added new tests where possible~

Adding plan error as bot response message

---

.github/workflows/copilot-deploy-plugins.yml

Incorrect artifact path in the plugin deployment workflow is causing the deployment to fail.
Fix the path.

Fix artifact path in plugin deployment workflow

---

webapi/Controllers/MaintenanceController.cs
webapp/src/App.tsx
webapp/src/components/views/BackendProbe.tsx

when the `ChatMigrationStatus` is set to `RequiresUpgrade`, the frontend will hang while seemingly nothing happens in the backend. changing the backend to only send the `MaintenanceResult` when an upgrade is happening fixes this.

Fix hanging when status is RequiresUpgrade

---

webapi/Controllers/MaintenanceController.cs
webapi/Services/MemoryMigration/ChatMigrationMonitor.cs
webapi/Services/SemanticKernelProvider.cs
webapp/src/components/views/BackendProbe.tsx

Muliple instances of VolatileMemory do not share state.

Volatile memory singleton for memory "migration"

---

webapp/src/index.tsx

addresses #485
casting leads to errors 😢

Fix error loading user on refresh

---

scripts/deploy/deploy-azure.ps1
scripts/deploy/deploy-azure.sh
scripts/deploy/main.bicep
scripts/deploy/main.json

Current Azure ARM template is not functional
- Remove embedding storage methods no longer support (Volatile and PostGres)
- Merge the 3 app insights into 1
- Have a single switch for whether to deploy binary packages
- Remove obsolete MemoryStore app settings
- Add Qdrant settings to SemanticMemory:Services
- Add memory pipeline service to Qdrant vnet

Fix fatal issues with Azure deployment templates

---

scripts/deploy/main.bicep
scripts/deploy/main.json

Using the deployment scripts or Deploy to Azure button is broken when using an OpenAI account (as opposed to an AOAI one).
Create the proper settings in the bicep/ARM template

Fix deployment when using OpenAI (as opposed to AOAI)

---

webapp/src/components/views/BackendProbe.tsx
webapp/src/libs/services/BaseService.ts
webapp/src/libs/services/MaintenanceService.ts

the call to `/healthz` isn't needed since we can determine if the backend is down when calling `/maintenanceStatus`.
the call to `/maintenanceStatus` throws a 401 when AAD is used since the token is not passed. noticed this when fixing #485.

Remove /healthz call + use token when calling /maintenanceStatus

---

.github/workflows/copilot-build-backend.yml
.github/workflows/copilot-deploy-backend.yml
.gitignore
scripts/deploy/deploy-webapi.ps1
scripts/deploy/deploy-webapi.sh
scripts/deploy/package-webapi.ps1
scripts/deploy/package-webapi.sh
webapp/src/libs/services/BaseService.ts

Some switches need to be included at the command line to ensure proper modification of the AAD app registration and addition of our URIs to the plugin CORS. These steps should be done by default.
Make all required steps run by default.
Fixed population of frontend version info

Make deploy-webapi do all it needs to by default

---

docker/webapi/.env.example

docker/webapi/.env.example should have below settings as the template to create .env file, otherwise, webapi container will failed to start
```
SemanticMemory__Services__AzureBlobs__Auth=
SemanticMemory__Services__AzureBlobs__ConnectionString=
```
docker/webapi/.env.example should have below settings as the template to create .env file, otherwise, webapi container will failed to start
```
SemanticMemory__Services__AzureBlobs__Auth=
SemanticMemory__Services__AzureBlobs__ConnectionString=
```

Add blobs settings in webapi docker .env.example

---

.gitignore
memorypipeline/CopilotChatMemoryPipeline.csproj
memorypipeline/appsettings.json
shared/CopilotChatShared.csproj
webapi/CopilotChatWebApi.csproj
webapi/Extensions/ISemanticMemoryClientExtensions.cs
webapi/appsettings.json

1. Semantic-Memory is being renamed and repackage.
1. Semantic-Kernel is also going through march to release (currently beta3)
1. CC and SM both have dependency on SK. 
1. Ideally CC and SM should update to the same SK beta (SM first and then CC)
1. This is the final available update of SM for CC prior to any SK beta update and includes functional and stabilization updates

Update to "final" semantic-memory package

---

.github/workflows/copilot-build-backend.yml
webapi/Extensions/SemanticKernelExtensions.cs
webapi/Extensions/ServiceExtensions.cs
webapi/Models/Response/ChatArchive.cs
webapi/Program.cs
webapi/README.md

and replace "Copilot Chat" with "Chat Copilot" to test it
Save time by not building the frontend files when we only are doing a PR for backend files
Remove the "=" that was messing up the boolean evaluation.
Replace a bunch of "Copilot Chat" strings with "Chat Copilot" to verify fix.

Fix condition to skip building frontend

---

webapi/Skills/Utils/TokenUtils.cs

We encountered some performance issues and implemented the following fix. 
We updated the TokenUtils class within the Skills Web API to address these issues. A newly-introduced tokenizer has been implemented for encoding text, which significantly improves the efficiency of the TokenCount method. As a result of this change, the performance of the token counting operations has been enhanced, ensuring more accurate and faster responses for users.

TokenCount  performance issues

---

webapi/Controllers/ChatController.cs
webapi/Controllers/PluginController.cs
webapi/Controllers/SpeechTokenController.cs
webapi/Extensions/SemanticKernelExtensions.cs
webapi/Program.cs
webapi/Services/SemanticKernelProvider.cs

To reduce the latency between for requests, we can re-use connections.
Use IHttpClientFactory to pool and re-use underlying HttpClientMessageHandler instances.

Use IHttpClientFactory

---

webapi/Extensions/ISemanticMemoryClientExtensions.cs

Customer reported issue.  Thank you!
- Extract documentId from partition link
- Parallelize tasks

Fix Document/Memory Removal when Chat Deleted

---

integration-tests/ChatCopilotIntegrationTests.csproj
memorypipeline/CopilotChatMemoryPipeline.csproj
memorypipeline/README.md
memorypipeline/appsettings.json
plugins/web-searcher/WebSearcher.csproj
shared/CopilotChatShared.csproj
shared/MemoryClientBuilderExtensions.cs
shared/MemoryConfiguration.cs
shared/Ocr/ConfigurationExtensions.cs
tools/importdocument/ImportDocument.csproj
webapi/Controllers/ChatMemoryController.cs
webapi/Controllers/DocumentController.cs
webapi/CopilotChatWebApi.csproj
webapi/Extensions/ISemanticMemoryClientExtensions.cs
webapi/Models/Storage/CitationSource.cs
webapi/Models/Storage/MemoryTags.cs
webapi/Options/PromptsOptions.cs
webapi/README.md
webapi/Services/MemoryMigration/IChatMemoryMigrationService.cs
webapi/Services/SemanticKernelProvider.cs
webapi/Skills/ChatSkills/ChatSkill.cs
webapi/Skills/ChatSkills/ExternalInformationSkill.cs
webapi/Skills/ChatSkills/SemanticChatMemoryExtractor.cs
webapi/Skills/ChatSkills/SemanticMemoryRetriever.cs
webapi/appsettings.json
webapp/public/index.html
webapp/src/components/chat/plan-viewer/PlanViewer.tsx

In anticipation of SK 1.0, we need to make some changes to CC.
- Upgraded SK to 1.0 Beta 5
- Upgraded other NuGets to higher versions
- Changed references to Semantic Memory to be to Kernel Memory instead
- Switched from using BasicPromptTemplateEngine to BasicPromptTemplateFactory
- Changed some "Copilot Chat" strings to "Chat Copilot" in the frontend

Upgrade CC to use SK 1.0 Beta 5

---

webapi/Controllers/ChatArchiveController.cs
webapi/Controllers/ChatHistoryController.cs
webapi/Models/Storage/ChatSession.cs
webapi/Plugins/Chat/ChatPlugin.cs

Stored system prompt references `TimeSkill `plugin that has been renamed to `TimePlugin`.  
System prompts for each chat have been stored in cosmosdb.
Dynamically intercept system-prompt and replace plugin reference.

Introduce "Safe" SystemDescription

---

plugins/web-searcher/WebSearcher.csproj
plugins/web-searcher/local.settings.json

Azure functions tend to break silently when the `Microsoft.Azure.Functions.*` packages are not of the correct versions. With the current versions, the web-searcher plugin cannot find the functions using the function core tool, i.e. `func start`. 
Downgrade the `Microsoft.Azure.Functions.*` versions to previous ones that have been tested extensively.

Revert updates to Microsoft.Azure.Functions.* packages for plugins

---

memorypipeline/CopilotChatMemoryPipeline.csproj
shared/CopilotChatShared.csproj
webapi/Controllers/ChatController.cs
webapi/CopilotChatWebApi.csproj
webapi/Services/SemanticKernelProvider.cs

A few breaking changes occurred in SK 1.0.0 beta 6
Update to SK 1.0.0 beta 6 and adapt code to support the breaking changes from the library

Update CC to SK 1.0.0 Beta 6

---

.github/workflows/markdown-link-check-config.json

No PRs can be merged due to 403 on https://platform.openai.com
This is NOT a permanent fix as it does NOT address the root cause.
It is a temporary change so important PRs can be merged.

OpenAI 403 workaround to merge approved PRs

---

scripts/deploy/main.bicep
scripts/deploy/main.json

The templates are currently prone to failure.
- Only use virtual nets when using Qdrant (it seems _something_ with the virtual nets is causing deployments to often fail)
- Automatically populate azureAdTenantId
- Force user to provide an API key and client IDs (instead of allowing unusable deployments to be created)

Make deployment template more robust

---

webapi/Controllers/ChatController.cs

We are currently, using OpenApiFunctionExecutionParameters to import OpenAI functions, which is incorrect and doesn't work.
Use OpenApiFunctionExecutionParameters to load OpenAI functions

Use ImportOpenAIPluginFunctionsAsync to import OpenAI functions

---

memorypipeline/README.md
tools/importdocument/Program.cs
tools/importdocument/README.md
webapi/Extensions/ServiceExtensions.cs
webapi/Options/ServiceOptions.cs
webapi/Plugins/Chat/ExternalInformationPlugin.cs
webapi/Program.cs
webapi/Services/AzureContentSafety.cs

Chat Copilot used to be called Copilot Chat.
Change strings to reflect new reality

Change instances of "Copilot Chat" to "Chat Copilot"

---

webapp/src/components/chat/chat-list/ChatList.tsx

This PR removes part of the isFiltering conversations view state, including an unnecessary filteredConversations field, since @TaoChenOSU's filters and sorts the conversations into the expected Latest and Older conversations lists.
Also, fixes a bug so the filter is applied to the client view name, rather than the actual saved name on the object since this is what our end user sees and would expect the search text to check against.

Fixing conversation filtering

---

.github/workflows/copilot-test-e2e.yml

The e2e test action is still having some issue starting the service. The action keeps failing and blocking PRs from merging.
Do not trigger this action when a PR is approved.

Do not trigger e2e test when a PR is approved

---

integration-tests/StaticFiles.cs
scripts/deploy/package-webapi.ps1
scripts/deploy/package-webapi.sh

We want static files to be properly served by the backend
- Copy folder contents of "build" instead of folder itself
- Add int test to check for presence of static files

Copy static files in proper folder

---

webapp/src/components/chat/ChatInput.tsx
webapp/src/components/chat/ChatRoom.tsx
webapp/src/components/chat/chat-history/ChatHistory.tsx
webapp/src/components/chat/chat-history/ChatHistoryItem.tsx

Chat-Copilot layout a little awkward for various layouts (UX Responsive)
https://github.com/microsoft/chat-copilot/issues/522
#UX Side-by-Side
---
**Current**:
**Updated**:
**Current**:
**Updated**:
**Current**:
**Updated**:
**Current**:
**Updated**:

Fix chatstyling

---

.github/labeler.yml

to unblock PRs
follows guidance from [labeler's release notes](https://github.com/actions/labeler/releases)

Update labeler.yml to v5

---

.github/labeler.yml

Use array for labeler glob patterns

---

webapi/README.md

Readme updated with example of what is required to include prompt.txt in build output

Issue #701 updated readme.md for webapi to make it clearer how one can include plugins in build output for publishing

---

webapp/src/components/chat/chat-history/ChatHistoryItem.tsx

1. Why is this change required?
UX
2. What problem does it solve?
Improve user experience when need copy chat history item
If the current message is from a bot and if the message has a prompt, it renders a Tooltip component with a Button inside it.
The Tooltip component is used to display a small pop-up box when the user hovers over an element. The content of the Tooltip changes based on the state of messagedCopied. If messagedCopied is true, the Tooltip displays 'Copied', otherwise, it displays 'Copy text'.
Inside the Tooltip, there is a Button component. The icon of the Button changes based on the messagedCopied state. If messagedCopied is true, it shows a ClipboardTask20Regular icon, otherwise, it shows a Clipboard20Regular icon.
The Button has an onClick event handler that triggers …

Included button to copy chat history item

---

webapi/Extensions/ServiceExtensions.cs
webapi/Program.cs

Removed required DI as part of https://github.com/microsoft/chat-copilot/pull/791.
Restore expected contact with empty action array.

.Net - Fix maintenance-middleware DI

---

webapi/Options/DocumentMemoryOptions.cs
webapi/Plugins/Chat/ChatPlugin.cs
webapi/Services/SemanticKernelProvider.cs
webapi/appsettings.json

Memory migration has been removed but some of its code was still present.
Remove leftover memory migration code

Remove remnants of memory migration

---

webapi/Plugins/Chat/ChatPlugin.cs
webapi/Plugins/Utils/TokenUtils.cs

OpenAI inserts a message under the hood for which we don't account, and thus throwing off our token budgeting. This causes us to sometimes send too many tokens when we approach a model's token limit. This results in errors.
Account for the OpenAI message inserted in our requests.

Fix token budgeting

---

webapi/Plugins/Chat/ChatPlugin.cs

Some dead wood is present in our code due to churn.
Remove dead paths.

Remove unused code path in HandleBotResponseAsync()

---

scripts/.env
scripts/Configure.ps1
scripts/Variables.ps1
scripts/configure.sh

There is some dead code related to planners in scripts
Remove dead code

Remove remnants of planners in scripts

---

shared/ServiceConfiguration.cs
webapi/appsettings.json

Due to changes in KernelMemory, providing alternative names now causes the system to die.
Only provide correct config section names.

Provide only correct names to ConfigureQueueDependency()

---

.github/workflows/copilot-deploy-backend.yml
.github/workflows/copilot-deploy-environment.yml
.github/workflows/copilot-deploy-infra.yml
.github/workflows/copilot-deploy-memorypipeline.yml
.github/workflows/copilot-deploy-pipeline.yml
.github/workflows/copilot-deploy-plugins.yml
.github/workflows/copilot-run-integration-tests.yml
.github/workflows/copilot-test-e2e.yml

We want integration tests to work
Remove some of the redundancy and make integration tests take proper input

Simplify GitHub actions and fix parts of integration testing

---

webapi/Plugins/Chat/ChatPlugin.cs
webapi/Plugins/Chat/SemanticChatMemoryExtractor.cs
webapi/Plugins/Utils/TokenUtils.cs

The user message is not added to the GPT completion request when the token count of the prompt exceeds 50% of the configuration.
This fix is inspired by #836
Fix budget calculation and clarify / simplify code.

Fix token budget + Clarify code

---

webapi/Extensions/ISemanticMemoryClientExtensions.cs

fix bug related to issue #851.
Unused parameter relevanceThreshold is passed to SearchAsync method to ensure only relevant documents are fetched.
Please help reviewers and future users, providing the following information:
1. The code change is related because current code retrieves all memory items regardless of similarity which prevents adding new memory items. Check SemanticChatMemoryExtractor.ExtractCognitiveMemoryAsync.
2. The issue is only the first memory item is preserved. Additional memory items are lost because they always seem to be similar to the first memory item.
3. With this fix, a memory item is skipped only if there is similar memory item in the memory. As a result distinct memory items will be preserved.
4. It fixes an open issue #851 .
The chance is simple, it utilizes …

Fixes #851 : relevanceThreshold is not utilized preventing additional memory items

---

webapp/src/App.tsx
webapp/src/components/chat/Chat.tsx

1. Why is this change required?
- This change is required to improve the modularity and readability.
2. What problem does it solve?
- This change reduces the complexity of the app.tsx file by isolating the `<Chat />` component into its own file.
3. What scenario does it contribute to?
- This contributes to scenarios where developers need to work on or debug the `<Chat/>` component independently of the main app logic. It also makes it easier for new developers to understand the structure of the application.
4. If it fixes an open issue, please link to the issue here.
- Not applicable/This PR does not address a specific open issue.
In this PR, I have created a new file named `Chat.tsx` and moved the relevant JSX and TypeScript code from app.tsx into this new component file. The main goals …

move Chat component logic to separate file

---

webapi/Extensions/ISemanticMemoryClientExtensions.cs

The current implementation does not delete chat documents and embeddings.
Fixes microsoft/chat-copilot#946
This change allows us to delete chat documents and vectors when a chat is deleted to avoid keeping unused documents and vectors in the memory store

fix: remove chat memories not selecting the right document id values /webapi

---

webapi/Controllers/ChatMemoryController.cs
webapi/Plugins/Chat/SemanticChatMemoryExtractor.cs

Model hasn't been generating JSON consistently for memory extraction. 
Set the response format to JSON to force the model to output valid json for memory extraction.

Fix memory extraction json format issue

---

webapp/src/App.tsx
webapp/src/components/chat/Chat.tsx

When the application initially starts without any chat sessions in the database, the app will attempt to create a new one. Currently, the app will attempt multiple times without waiting for the initial attempt to finish. This PR fixes the issue by introducing an intermediate state.

Fix: Load multiple chats during first startup
