microsoft/chat-copilot

README.md
deploy/deploy-azure.ps1
deploy/deploy-azure.sh
deploy/deploy-webapp.ps1
deploy/deploy-webapp.sh
deploy/main.bicep
deploy/main.json

We want the deployment templates support ACS
Augment the templates so that they support ACS in addition to Qdrant for storage of embeddings

Make templates support Azure Cognitive Search

---

webapi/CopilotChat/Controllers/ChatController.cs
webapi/CopilotChat/Controllers/DocumentImportController.cs
webapi/CopilotChat/Hubs/MessageRelayHub.cs
webapi/CopilotChat/Skills/ChatSkills/ChatSkill.cs
webapp/src/components/chat/ChatInput.tsx
webapp/src/components/chat/ChatRoom.tsx
webapp/src/components/chat/plan-viewer/PlanViewer.tsx
webapp/src/libs/models/ChatMessage.ts
webapp/src/libs/services/ChatService.ts
webapp/src/redux/features/conversations/conversationsSlice.ts
webapp/src/redux/features/message-relay/signalRMiddleware.ts

responses will now be streamed directly from the Kernel to all users in the chat. 
- `ChatSkill.cs`:
-  added `StreamResponseToClient()` to broadcast the streamed response to all clients.
- changed `GetChatResponseAsync()` to use `Task.WhenAll` when extracting audience/user intent and semantic/document memories.
- changed `GetChatContextTokenLimit()` to account for the tokens used in extracting the audience
**regular messages:**
**planner messages:**
**multiuser messages:**

Add support for chat streaming

---

webapi/CopilotChat/Controllers/DocumentImportController.cs
webapi/CopilotChat/Models/MemorySource.cs
webapp/src/components/chat/ChatInput.tsx
webapp/src/components/chat/ChatResourceList.tsx
webapp/src/components/chat/ChatWindow.tsx
webapp/src/components/shared/Alerts.tsx
webapp/src/libs/models/ChatMemorySource.ts
webapp/src/redux/features/conversations/ChatState.ts
webapp/src/redux/features/conversations/conversationsSlice.ts

Refactor files tab to documents tab.
1. Enable document import in the documents tab.
2. Show progress on each document importing.
3. Show token usage of each imported document.
4. Move alerts to the bottom of the screen.
5. 5. Add support for markdown files.

Add documents tab

---

.github/workflows/label-pr.yml

adds workflow to enable the Labeler action

Add Labeler workflow

---

webapp/src/components/chat/ChatInput.tsx

this small change allows users to chat with one less click 🖱️
autofocuses on the chat text area whenever the selected chat changes (new chats included).

Add auto focus to ChatInput

---

.github/workflows/copilot-deploy-backend.yml

Removing output from settings update command.

---

webapi/CopilotChat/Skills/ChatSkills/ExternalInformationSkill.cs
webapi/README.md
webapi/appsettings.json
webapp/src/components/chat/plan-viewer/PlanStepInput.tsx

The ExternalInformationSkill now includes a ResultHeader and functionsUsed in AcquireExternalInformationAsync response. Additionally, the comment for the Planner:Type setting has been updated to include a note about using SequentialPlanner with `gpt-4` to optimize capabilities
- ExternalInformationSkill:
- Added a ResultHeader constant to indicate plan results.
- Added a functionsUsed constant to indicate the functions executed in the plan.
- Updated the InvokeAsync method to include the ResultHeader and functionsUsed in the response.
- PlanStepInput:
- Fixed bug on cancel, to reset the value, rather than exit editing mode
- Updated the onCancel function to set the isEditingInput state based on the input value.
- Updated the configuration instructions for the Planner in the …

Update SequentialPlanner Configuration Instructions + improved ExternalInformationSkill and PlanStepInput

---

webapi/CopilotChat/Controllers/ChatMemoryController.cs

fixes new error: https://github.com/microsoft/chat-copilot/security/code-scanning/5

Fix CodeQL error

---

webapi/CopilotChat/Models/BotResponsePrompt.cs
webapi/CopilotChat/Options/PromptsOptions.cs
webapi/CopilotChat/Skills/ChatSkills/ChatSkill.cs
webapp/src/components/chat/prompt-dialog/PromptDialog.tsx
webapp/src/libs/models/BotResponsePrompt.ts

This pull request refactors the PromptDialog component to improve readability and adds a new BotResponsePrompt model. 
The refactoring includes the addition of a PromptSectionsNameMap to store the names of the prompt sections. The BotResponsePrompt model includes fields for system persona, audience, user intent, chat memories, relevant knowledge, and system chat continuation. Additionally, the ChatSkill class has been updated to use the new model when streaming responses to the client.
- Refactored PromptDialog component to improve readability.
- Added PromptSectionsNameMap to store the names of the prompt sections.
- Added BotResponsePrompt model with fields for system persona, audience, user intent, chat memories, relevant knowledge, and system chat continuation.
- Updated ChatSkill.cs …

Add BotResponsePrompt model and Refactor PromptDialog

---

webapi/CopilotChat/Controllers/DocumentImportController.cs
webapp/src/components/chat/chat-history/ChatHistory.tsx
webapp/src/components/chat/chat-history/ChatHistoryDocumentContent.tsx
webapp/src/components/chat/chat-list/ChatListItem.tsx
webapp/src/components/chat/tabs/DocumentsTab.tsx
webapp/src/styles.tsx

resolves #49.
- `DocumentImportController`: changed to use `Task.WhenAll` when importing documents.
- all other files: changed to show overflow text on hover and to truncate long document names (shown below).

Upload documents in parallel + truncate text for long document names

---

scripts/deploy/deploy-webapp.ps1
scripts/deploy/deploy-webapp.sh

fixing paths now that the scripts have been moved to `deploy/`.

Fix relative paths in deploy scripts

---

README.md

The link to the application registration section has become zombied.
Re-targeted existing reference.

Fix app registration link in README

---

README.md

A gif with better quality needed on primary Readme.
Replaces current image with gif used on learn docs and semantic kernel primary Readme.

Update Chat Copilot gif on primary Readme.md

---

.github/workflows/codeql-analysis.yml
webapi/Controllers/ChatMemoryController.cs
webapp/tests/utils.ts

- changes the fix for the C# CodeQL alerts to be closer to the recommended solution since the code is still being flagged: https://github.com/microsoft/chat-copilot/security/code-scanning/7
my guess is that the alerts are still firing because the tool sees the input variable (`memoryName`) used on the same line as `LogWarning()` with no explicit call to `.Replace()`:
- updates the CodeQL config to also run on JS/TS files as well, which finds 2 alerts in the tests: https://github.com/dehoward/chat-copilot/security/code-scanning/6

Fix C# CodeQL alerts + add JS/TS to CodeQL

---

.github/workflows/memorypipeline-build.yml

Fix the memory pipeline build csproj file name

---

webapi/nuget.config

Fix webapi semantic memory package ref

---

.github/workflows/copilot-build-backend.yml

Fix webapi package pipeline command line continuation

---

webapi/Extensions/ServiceExtensions.cs

Fix typo in ServiceExtensions

---

webapi/Extensions/SemanticMemoryExtensions.cs
webapi/Extensions/ServiceExtensions.cs

Fix SemanticMemoryExtensions.cs formatting

---

webapi/Extensions/SemanticMemoryExtensions.cs

Sort SemanticMemoryExtensions.cs imports

---

scripts/deploy/main.json

Updating template hash to match bicep file.

Updating template hash.

---

webapi/Controllers/DocumentImportController.cs
webapi/Models/Response/BotResponsePrompt.cs
webapi/Skills/ChatSkills/ChatSkill.cs
webapi/Skills/ChatSkills/ExternalInformationSkill.cs
webapi/appsettings.json
webapp/src/App.tsx
webapp/src/components/chat/prompt-dialog/PromptDialog.tsx
webapp/src/components/chat/tabs/PlansTab.tsx
webapp/src/components/header/UserSettingsMenu.tsx
webapp/src/components/open-api-plugins/plugin-wizard/PluginWizard.tsx
webapp/src/components/token-usage/TokenUsageGraph.tsx
webapp/src/components/token-usage/TokenUsageLegendItem.tsx
webapp/src/components/views/Login.tsx
webapp/src/libs/models/BotResponsePrompt.ts
webapp/src/redux/features/plugins/pluginsSlice.ts

A variety of functional improvements, including:
- Adding supplement to ExternalInformation section of plan to help provide model more guidance.
- Adding tabs in prompt dialog to support view of raw rendered prompt content
- Fixing a bug to support .md file import
- In formatted prompt, added explicit message to indicate no relevant document memories were used in rendered prompt
- Note "Coming soon" for planner token usage
- Frontload custom plugins when they're added
- Align Login View
- Header corner items won't show on app launch up pages (i.e., backend probe page)
New login view
Update prompt dialog with tabs
Support .md files
~~- [ ] All unit tests pass, and I have added new tests where possible~~

Functional improvements + bug squashing

---

scripts/deploy/deploy-azure.sh
scripts/deploy/deploy-webapi.sh
scripts/deploy/deploy-webapp.sh
scripts/deploy/package-webapi.sh

Found copy & paste errors in our deployment scripts usage descriptions. They don't match the actual options.
Clean the usage descriptions for the deployment scripts.

Clean deployment scripts usage descriptions

---

.github/workflows/copilot-deploy-frontend.yml
scripts/deploy/deploy-webapp.sh

I introduced a bug with https://github.com/microsoft/chat-copilot/pull/165 in the frontend deployment script
Use proper Unix commands in the shell script

Fix Unix deployment of frontend

---

.github/workflows/copilot-build-backend.yml
.github/workflows/copilot-deploy-pipeline.yml
.github/workflows/memorypipeline-build.yml
memorypipeline/CopilotChatMemoryPipeline.csproj
webapi/CopilotChatWebApi.csproj
webapi/nuget.config

Acquire SemanticMemory from a public feed

---

.github/workflows/copilot-build-memorypipeline.yml

Set fetch depth to 0 for GitVersion to work

---

.github/workflows/copilot-deploy-pipeline.yml
memorypipeline/BuilderExtensions.cs
memorypipeline/Program.cs

Fix deploy pipeline needs and import ordering

---

scripts/deploy/main.bicep
scripts/deploy/main.json

Add addition params of web api to main bicep

---

webapi/Extensions/SemanticKernelExtensions.cs
webapi/Options/MemoryStoreOptions.cs

added more generic exception message and summary

---

.github/pull_request_template.md
.github/workflows/markdown-link-check-config.json
CONTRIBUTING.md
scripts/deploy/README.md

Fixing broken links and links that point to the wrong repository.

Updating broken links and links to wrong repository.

---

README.md

Updated scripts/README.md, clarifying the installation script file name.
- [x ] The code builds clean without any errors or warnings
- [ x] The PR follows the [Contribution Guidelines](https://github.com/microsoft/chat-copilot/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/chat-copilot/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [ x] I didn't break anyone :smile:

doc: :pencil2: Update README.md clarifying install script.

---

webapi/Controllers/ChatController.cs
webapi/Controllers/DocumentImportController.cs
webapi/CopilotChatWebApi.csproj
webapi/Services/AzureContentSafety.cs
webapi/Skills/ChatSkills/ChatSkill.cs

Updating SK packages to latest version: 0.23.230906.2-preview
- Changing AIException -> SKException 
- using `Microsoft.SemanticKernel.TemplateEngine.Prompt` specifically
~- [ ] All unit tests pass, and I have added new tests where possible~

Updating SK packages to 0.23.230906.2-preview

---

webapi/Controllers/MaintenanceController.cs
webapi/Models/Response/MigrationResult.cs
webapi/Options/ServiceOptions.cs
webapi/Program.cs
webapi/Services/MaintenanceMiddleware.cs
webapi/appsettings.json
webapp/src/App.tsx
webapp/src/components/chat/chat-list/ChatList.tsx
webapp/src/components/views/BackendProbe.tsx
webapp/src/redux/features/app/AppState.ts
webapp/src/redux/features/app/appSlice.ts
webapp/src/redux/features/message-relay/signalRHubConnection.ts

In order to support maintenance modes that might disrupt service availability (such as a storage update), adding support to put app into a maintenance mode.

Maintenance framework

---

webapi/Controllers/ServiceOptionsController.cs
webapi/Skills/ChatSkills/SemanticMemoryRetriever.cs
webapp/src/components/chat/chat-history/ChatHistoryTextContent.tsx
webapp/src/components/utils/TextUtils.tsx

Citing the sources at the end of the sentence.

Inline citations

---

scripts/deploy/main.bicep
scripts/deploy/main.json

Changing the name of the App Service Plan will break the existing deployment.
Revert the name change.

Revert deployment asp name change

---

.github/workflows/copilot-test-e2e.yml
memorypipeline/appsettings.json
webapi/appsettings.json
webapp/tests/utils.ts

We changed the settings structure in the Semantic Memory PR. Need to update the e2e test action yaml file to reflect the changes for the tests to run.
1. Update copilot-test-e2e.yml
2. Refactor some default settings for easier temporary file management.
3. Reduce the test timeouts to avoid hanging tests.

Update e2e test action for new settings

---

README.md

Update readme for PowerShell Core 6+

---

webapp/src/components/chat/ChatRoom.tsx
webapp/src/libs/hooks/useChat.ts

Address https://github.com/microsoft/chat-copilot/issues/371
1. When a selected conversation is hidden, keep it hidden and show a message.
2. After deleting a conversation, and all other conversations are hidden, automatically create a new chat.

Keep hidden conversations invisible

---

webapi/Program.cs
webapi/Storage/Repository.cs

Repository TryFindByIdAsync would not try to find anything if no callback was passed to it, hence always returning true, even when no entries were found!
Always doing a true search because executing any callback with the result.

Fix repository TryFindByIdAsync

---

.github/workflows/copilot-deploy-plugins.yml
scripts/deploy/deploy-plugins.ps1
scripts/deploy/deploy-plugins.sh

The GitHub action is getting a permission denial error when running the script to deploy the plugins.
This could be due to the copy & paste error in the deployment scripts.

Fix Copy and Paste error in plugins deployment scripts

---

tools/importdocument/Program.cs
webapi/Extensions/ServiceExtensions.cs
webapp/src/libs/services/ChatService.ts

1. Fix error in chat route
2. Fix error in import document route
3. Add PATCH to CORS allowed methods

Miscellaneous fixes

---

scripts/deploy/main.bicep
scripts/deploy/main.json

Two configs in the deployment templates have the wrong names.
Fix the names.

Update deployment template with the correct param name

---

webapp/src/libs/services/ChatService.ts

Fixes #454 - error in route the frontend is using to process plans

Fix route for processing plans

---

scripts/deploy/deploy-webapi.ps1
scripts/deploy/deploy-webapi.sh
scripts/deploy/deploy-webapp.ps1
scripts/deploy/deploy-webapp.sh

This pull request introduces an enhancement to the deploy-webapi and deploy-webapp scripts by enabling the optional use of Azure App Service Deployment Slots and Static Web App Preview Environments respectively. This feature addresses the challenge of achieving zero-downtime deployments, ensuring that our application remains accessible and functional during updates. Deployment slots allow us to validate application changes in a staging environment that mirrors production, facilitating extensive testing and verification before the swap. This guarantees that only thoroughly vetted and approved changes reach the live environment, enhancing our deployment confidence and application reliability. Moreover, in the rare case of an issue arising post-deployment, the slots provide an instant …

Add Support for deployment slots in deployment scripts

---

webapi/Controllers/DocumentController.cs
webapi/Extensions/ISemanticMemoryClientExtensions.cs
webapi/Options/DocumentMemoryOptions.cs
webapi/Skills/ChatSkills/ChatSkill.cs
webapi/Skills/ChatSkills/SemanticMemoryRetriever.cs

1. Issue reported by the community: https://github.com/microsoft/chat-copilot/issues/421
2. Citation was accidentally removed by a previous PR.
1. Fix the issue.
2. Add back citations.

Fix global document retrieval and citations

---

webapi/Options/MemoryStoreType.cs

- This fixes #562
- Fixes the Error: 500: System.ArgumentException: 
Invalid memory store type: Disk

Fix invalid memory store type: Disk

---

scripts/deploy/main.json

Fix template for proper tracking
Generated new hash with "az bicep"

Fix template hash

---

webapp/src/components/chat/chat-history/ChatHistoryItem.tsx
webapp/src/components/chat/chat-list/ChatListSection.tsx

Fix for dependabot

---

README.md
integration-tests/ChatCopilotIntegrationTests.csproj
memorypipeline/CopilotChatMemoryPipeline.csproj
plugins/README.md
plugins/shared/PluginManifest.cs
shared/CopilotChatShared.csproj
tools/importdocument/ImportDocument.csproj
webapi/CopilotChatWebApi.csproj
webapi/Models/Storage/ChatMessage.cs
webapi/Utilities/PluginUtils.cs
webapp/src/components/open-api-plugins/plugin-wizard/steps/EnterManifestStep.tsx

Getting the latest and greatest
Update nugets

Update to SK 1 beta 7

---

README.md
integration-tests/ChatCopilotIntegrationTests.csproj
memorypipeline/CopilotChatMemoryPipeline.csproj
plugins/README.md
plugins/shared/PluginManifest.cs
shared/CopilotChatShared.csproj
webapi/Controllers/ChatArchiveController.cs
webapi/Controllers/ChatHistoryController.cs
webapi/Controllers/DocumentController.cs
webapi/CopilotChatWebApi.csproj
webapi/Extensions/ISemanticMemoryClientExtensions.cs
webapi/Extensions/ServiceExtensions.cs
webapi/Models/Response/ChatArchive.cs
webapi/Models/Response/CreateChatResponse.cs
webapi/Models/Storage/CopilotChatMessage.cs
webapi/Plugins/Chat/ChatPlugin.cs
webapi/Plugins/Utils/PromptUtils.cs
webapi/Plugins/Utils/TokenUtils.cs
webapi/Storage/ChatMessageRepository.cs
webapi/Utilities/PluginUtils.cs
webapp/src/components/open-api-plugins/plugin-wizard/steps/EnterManifestStep.tsx

Keeping up with the latest and greatest
Update NuGets

Update to SK 1.0 beta 8

---

webapp/yarn.lock

We exit on attempted changes to our yarn.lock file.
- Update yarn.lock so that it doesn't require changes to work.
- Deduplicate package versions

Fix yarn.lock file and run deduplicate on it to unify versions

---

.github/workflows/copilot-deploy-pipeline.yml

Main deployment pipeline got broken by recent change to int test pipeline,
Remove unused param that makes pipeline choke.

Fix deployment pipeline

---

.github/workflows/copilot-run-integration-tests.yml

Secrets are not being passed properly in integration test workflow
Pass secrets properly

Fix passing of secrets for integration tests

---

scripts/deploy/package-memorypipeline.sh
scripts/deploy/package-plugins.sh
scripts/deploy/package-webapi.sh

Fix unix package scripts

---

memorypipeline/CopilotChatMemoryPipeline.csproj
shared/CopilotChatShared.csproj
webapi/CopilotChatWebApi.csproj

Getting the latest and greatest version dependencies
Getting the latest and greatest version dependencies

Update to latest SK version

---

.github/workflows/copilot-deploy-pipeline.yml

So that they can run
Provide environment to int tests

Provide environment to int tests

---

.github/workflows/copilot-deploy-backend.yml
.github/workflows/copilot-deploy-infra.yml
.github/workflows/copilot-deploy-memorypipeline.yml
.github/workflows/copilot-deploy-plugins.yml

Fix app ID used for workflow logins

Fix app ID used for workflow logins

---

.github/workflows/copilot-run-integration-tests.yml

Can't read secrets
Add resd secrets permission

Read secrets

---

.github/workflows/copilot-run-integration-tests.yml

This reverts commit 0b586b82cc4063bec7ce59ef2037698b628c87f2.

Revert "Read secrets (#849)"

---

webapp/src/index.tsx

Allow the project to work anonymously
Fix 'getLogger' error that prevent the webapp to start anonymously.

fix(webapp): Fix 989 issue

---

webapp/src/App.tsx

New linter chokes on an old line of code
Add {} to a line

Fix lint issue

---

webapp/src/App.tsx

The useEffect hook in the App component is causing an infinite rendering loop. Remove the dependencies that are causing the loop.

Fix: App component UseEffect infinite loop

---

README.md
plugins/web-searcher/WebSearcher.csproj
scripts/install-apt.sh
tools/importdocument/ImportDocument.csproj
webapi/CopilotChatWebApi.csproj
webapi/appsettings.json
webapp/package.json
webapp/yarn.lock

Upgrade all dependencies, except for SK and KM. 
Apply also security upgrades to frontend.
Fix scripts and documentation still pointing to .NET 7.

Upgrade frontend and backend dependencies
